### ISSUE TITLE
BUSCO: Docker container doesn't write any results onto the local file system! 

### ISSUE THREAD

**Issue by mscheremetjew** [mscheremetjew/workflow-is-cwl#11]
Container: comics/busco:3.0.2

**Comment by mr-c** [comment]
@mscheremetjew What about the biocontainers.pro version? https://quay.io/repository/biocontainers/busco?tab=tags

**Comment by mscheremetjew** [comment]
Thanks for the hint. I am not sure I've tested that one yet. I will give it a try.

**Comment by mscheremetjew** [comment]
Works now. https://travis-ci.org/mscheremetjew/workflow-is-cwl/jobs/425298403
