### ISSUE TITLE
FastQC: Create Docker container for version 0.11.7

### ISSUE THREAD

**Issue by mscheremetjew** [mscheremetjew/workflow-is-cwl#3]
Create a PR against: https://github.com/BioContainers/containers/tree/master/fastqc

**Comment by mr-c** [comment]
Good news, they already have 0.11.7: https://quay.io/repository/biocontainers/fastqc?tab=tags

`dockerPull: quay.io/biocontainers/fastqc:0.11.7--4`

**Comment by arnaudmeng** [comment]
@mr-c Thank you for your help. I Have tested the docker image and it works perfectly. 
I'll commit a new version for the FastQC tool definition using this Docker image.
