### ISSUE TITLE
Validating the complete assembly workflow

### ISSUE THREAD

**Issue by arnaudmeng** [mscheremetjew/workflow-is-cwl#32]
I'm working on the complete workflow validation. I've difficulties to figure out how to fix the issue below. Any idea ?

`
Tool definition failed validation:
../workflow-is-cwl-assembly/workflows/TranscriptomeAssembly-wf.cwl:155:5: Type property "['null', 'seq_type']" not a valid Avro schema: Union item must be a valid Avro schema: Could not make an Avro Schema object from seq_type.
`

Runned command : 

`cwltool --validate ../workflow-is-cwl-assembly/workflows/TranscriptomeAssembly-wf.cwl ../workflow-is-cwl-assembly/workflows/TranscriptomeAssembly-wf.test.job.paired-end.yaml`

**Comment by mscheremetjew** [comment]
@arnaudmeng This should be fixed now. I just pushed the fix to the assembly branch. Can you please test and close the ticket if it works!?

**Comment by arnaudmeng** [comment]
@mscheremetjew Thank you ! 
It now works, with the last push you've made I obtain a valid cwltools definition. 

Command: 
`
cwltool --validate ../workflow-is-cwl-assembly/workflows/TranscriptomeAssembly-wf.cwl TranscriptomeAssembly-wf.test.job.paired-end.yaml
`

Result: 
`
(...)
../workflow-is-cwl-assembly/workflows/TranscriptomeAssembly-wf.cwl is valid CWL.
`
