### ISSUE TITLE
Trinity: Add test inputs and expected outputs

### ISSUE THREAD

**Issue by mscheremetjew** [mscheremetjew/workflow-is-cwl#4]

**Comment by arnaudmeng** [comment]
@mscheremetjew I've fixed the Trinity tool definition so that it now handles multiple FASTQ inputs. 
Trinity test inputs and expected outputs have been added to the "utils" directory.

**Comment by mr-c** [comment]
@arnaudmeng I don't see any recent commits on the primary branch; where should I look?

**Comment by arnaudmeng** [comment]
Hi @mr-c 
Every recent commit have been done in the "assembly" branch.

**Comment by mscheremetjew** [comment]
@mr-c if you refer to master as primary, nothing has been committed for a while. dev and assembly are not stable/ready yet.
